package com.adrian.muscleforge.exercise

object ExerciseDataSeeder {

    //to poblate de db
    fun getInitialExercises(): List<Exercise> {
        return listOf(
            Exercise(name = "Press Banca", series = 0, repetitions = 0, weight = 0.0),
            Exercise(name = "Sillon de Cuadriceps", series = 0, repetitions = 0, weight = 0.0),
            Exercise(name = "Gemelos", series = 0, repetitions = 0, weight = 0.0),
            Exercise(name = "Biceps 1y1", series = 0, repetitions = 0, weight = 0.0),
            Exercise(name = "Sentadilla", series = 0, repetitions = 0, weight = 0.0),
            Exercise(name = "Hip Trust", series = 0, repetitions = 0, weight = 0.0)

//            Exercise(name = "Arnold Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Bench Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Deadlift", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Front Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Hip Thrust", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Overhead Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Shrug", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Barbell Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Battle Ropes", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Bent-Over Lateral Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Bent-Over Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Box Jump", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Bulgarian Split Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Bicep Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Chest Fly", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Crunch", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Lateral Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Rope Triceps Pushdown", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Seated Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cable Triceps Extension", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Calf Press on Leg Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Chest Dip", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Chin-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Clean and Jerk", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Concentration Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Cross Body Hammer Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Decline Bench Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Decline Crunch", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Decline Sit-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Bench Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Bicep Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Bulgarian Split Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Chest Fly", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Deadlift", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Front Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Hammer Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Lateral Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Lunges", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Overhead Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Pullover", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Rear Delt Fly", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Shrug", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Step-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Dumbbell Triceps Kickback", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Face Pull", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Farmer's Walk", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Flat Bench Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Front Dumbbell Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Front Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Glute Bridge", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Goblet Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Good Morning", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Hack Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Hammer Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Hanging Leg Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "High Pull", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Incline Bench Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Incline Dumbbell Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Incline Dumbbell Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Incline Push-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Inverted Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Jump Rope", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Jump Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Clean", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Deadlift", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Goblet Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Swing", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Turkish Get-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Kettlebell Windmill", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Landmine Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Lat Pulldown", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Lateral Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Leg Curl (Machine)", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Leg Extension (Machine)", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Leg Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Lunge", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Machine Chest Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Machine Row", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Medicine Ball Slam", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Mountain Climbers", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Overhead Squat", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Pectoral Fly (Machine)", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Pike Push-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Plank", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Power Clean", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Preacher Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Pull-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Push Press", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Push-Up", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Rear Delt Fly", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Romanian Deadlift", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Russian Twist", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Seated Calf Raise", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Seated Leg Curl", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Skull Crusher", series = 0, repetitions = 0, weight = 0.0),
//            Exercise(name = "Sled Push", series = 0, repetitions = 0, weight = 0.0)
        )
    }
}